/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as ContentCreateRouteImport } from './routes/content.create'
import { Route as PUsernameIndexRouteImport } from './routes/p.$username.index'
import { Route as ApiContentIndexRouteImport } from './routes/api.content.index'
import { Route as PUsernameContentIdRouteImport } from './routes/p.$username.$contentId'
import { Route as ContentIdEditRouteImport } from './routes/content.$id.edit'
import { Route as ApiUserProfileRouteImport } from './routes/api.user.profile'
import { Route as ApiUserUsernameRouteImport } from './routes/api.user.$username'
import { Route as ApiContentIdRouteImport } from './routes/api.content.$id'
import { Route as ApiContentContentIdRouteImport } from './routes/api.content.$contentId'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentCreateRoute = ContentCreateRouteImport.update({
  id: '/content/create',
  path: '/content/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PUsernameIndexRoute = PUsernameIndexRouteImport.update({
  id: '/p/$username/',
  path: '/p/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentIndexRoute = ApiContentIndexRouteImport.update({
  id: '/api/content/',
  path: '/api/content/',
  getParentRoute: () => rootRouteImport,
} as any)
const PUsernameContentIdRoute = PUsernameContentIdRouteImport.update({
  id: '/p/$username/$contentId',
  path: '/p/$username/$contentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentIdEditRoute = ContentIdEditRouteImport.update({
  id: '/content/$id/edit',
  path: '/content/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserProfileRoute = ApiUserProfileRouteImport.update({
  id: '/api/user/profile',
  path: '/api/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserUsernameRoute = ApiUserUsernameRouteImport.update({
  id: '/api/user/$username',
  path: '/api/user/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentIdRoute = ApiContentIdRouteImport.update({
  id: '/api/content/$id',
  path: '/api/content/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentContentIdRoute = ApiContentContentIdRouteImport.update({
  id: '/api/content/$contentId',
  path: '/api/content/$contentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/content/create': typeof ContentCreateRoute
  '/profile/edit': typeof ProfileEditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/content/$contentId': typeof ApiContentContentIdRoute
  '/api/content/$id': typeof ApiContentIdRoute
  '/api/user/$username': typeof ApiUserUsernameRoute
  '/api/user/profile': typeof ApiUserProfileRoute
  '/content/$id/edit': typeof ContentIdEditRoute
  '/p/$username/$contentId': typeof PUsernameContentIdRoute
  '/api/content': typeof ApiContentIndexRoute
  '/p/$username': typeof PUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/content/create': typeof ContentCreateRoute
  '/profile/edit': typeof ProfileEditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/content/$contentId': typeof ApiContentContentIdRoute
  '/api/content/$id': typeof ApiContentIdRoute
  '/api/user/$username': typeof ApiUserUsernameRoute
  '/api/user/profile': typeof ApiUserProfileRoute
  '/content/$id/edit': typeof ContentIdEditRoute
  '/p/$username/$contentId': typeof PUsernameContentIdRoute
  '/api/content': typeof ApiContentIndexRoute
  '/p/$username': typeof PUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/content/create': typeof ContentCreateRoute
  '/profile/edit': typeof ProfileEditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/content/$contentId': typeof ApiContentContentIdRoute
  '/api/content/$id': typeof ApiContentIdRoute
  '/api/user/$username': typeof ApiUserUsernameRoute
  '/api/user/profile': typeof ApiUserProfileRoute
  '/content/$id/edit': typeof ContentIdEditRoute
  '/p/$username/$contentId': typeof PUsernameContentIdRoute
  '/api/content/': typeof ApiContentIndexRoute
  '/p/$username/': typeof PUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/content/create'
    | '/profile/edit'
    | '/api/auth/$'
    | '/api/content/$contentId'
    | '/api/content/$id'
    | '/api/user/$username'
    | '/api/user/profile'
    | '/content/$id/edit'
    | '/p/$username/$contentId'
    | '/api/content'
    | '/p/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/content/create'
    | '/profile/edit'
    | '/api/auth/$'
    | '/api/content/$contentId'
    | '/api/content/$id'
    | '/api/user/$username'
    | '/api/user/profile'
    | '/content/$id/edit'
    | '/p/$username/$contentId'
    | '/api/content'
    | '/p/$username'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/content/create'
    | '/profile/edit'
    | '/api/auth/$'
    | '/api/content/$contentId'
    | '/api/content/$id'
    | '/api/user/$username'
    | '/api/user/profile'
    | '/content/$id/edit'
    | '/p/$username/$contentId'
    | '/api/content/'
    | '/p/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SignInRoute: typeof SignInRoute
  ContentCreateRoute: typeof ContentCreateRoute
  ProfileEditRoute: typeof ProfileEditRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiContentContentIdRoute: typeof ApiContentContentIdRoute
  ApiContentIdRoute: typeof ApiContentIdRoute
  ApiUserUsernameRoute: typeof ApiUserUsernameRoute
  ApiUserProfileRoute: typeof ApiUserProfileRoute
  ContentIdEditRoute: typeof ContentIdEditRoute
  PUsernameContentIdRoute: typeof PUsernameContentIdRoute
  ApiContentIndexRoute: typeof ApiContentIndexRoute
  PUsernameIndexRoute: typeof PUsernameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/create': {
      id: '/content/create'
      path: '/content/create'
      fullPath: '/content/create'
      preLoaderRoute: typeof ContentCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$username/': {
      id: '/p/$username/'
      path: '/p/$username'
      fullPath: '/p/$username'
      preLoaderRoute: typeof PUsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content/': {
      id: '/api/content/'
      path: '/api/content'
      fullPath: '/api/content'
      preLoaderRoute: typeof ApiContentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$username/$contentId': {
      id: '/p/$username/$contentId'
      path: '/p/$username/$contentId'
      fullPath: '/p/$username/$contentId'
      preLoaderRoute: typeof PUsernameContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$id/edit': {
      id: '/content/$id/edit'
      path: '/content/$id/edit'
      fullPath: '/content/$id/edit'
      preLoaderRoute: typeof ContentIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/profile': {
      id: '/api/user/profile'
      path: '/api/user/profile'
      fullPath: '/api/user/profile'
      preLoaderRoute: typeof ApiUserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/$username': {
      id: '/api/user/$username'
      path: '/api/user/$username'
      fullPath: '/api/user/$username'
      preLoaderRoute: typeof ApiUserUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content/$id': {
      id: '/api/content/$id'
      path: '/api/content/$id'
      fullPath: '/api/content/$id'
      preLoaderRoute: typeof ApiContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content/$contentId': {
      id: '/api/content/$contentId'
      path: '/api/content/$contentId'
      fullPath: '/api/content/$contentId'
      preLoaderRoute: typeof ApiContentContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SignInRoute: SignInRoute,
  ContentCreateRoute: ContentCreateRoute,
  ProfileEditRoute: ProfileEditRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiContentContentIdRoute: ApiContentContentIdRoute,
  ApiContentIdRoute: ApiContentIdRoute,
  ApiUserUsernameRoute: ApiUserUsernameRoute,
  ApiUserProfileRoute: ApiUserProfileRoute,
  ContentIdEditRoute: ContentIdEditRoute,
  PUsernameContentIdRoute: PUsernameContentIdRoute,
  ApiContentIndexRoute: ApiContentIndexRoute,
  PUsernameIndexRoute: PUsernameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
